export const modelOptions = [
  {
    id: 'gpt-4o',
    label: 'GPT-4o',
    provider: 'openai',
    version: '4o',
    description: 'Most advanced multimodal model from OpenAI, excelling in vision and audio understanding.',
    contextWindow: 128000,
    inputCostPer1kTokens: 0.005,
    outputCostPer1kTokens: 0.015,
  },
  {
    id: 'gpt-4o-mini',
    label: 'GPT-4o Mini',
    provider: 'openai',
    version: '4o-mini',
    description: 'More affordable and efficient version of GPT-4o, still highly capable.',
    contextWindow: 128000,
    inputCostPer1kTokens: 0.00015,
    outputCostPer1kTokens: 0.0006,
  },
  {
    id: 'gpt-4-turbo',
    label: 'GPT-4 Turbo',
    provider: 'openai',
    version: '4-turbo',
    description: 'Previous generation high-performance model from OpenAI with vision capabilities.',
    contextWindow: 128000,
    inputCostPer1kTokens: 0.01,
    outputCostPer1kTokens: 0.03,
  },
  {
    id: 'gpt-4',
    label: 'GPT-4',
    provider: 'openai',
    version: '4',
    description: 'Original GPT-4 model with strong reasoning and broad knowledge.',
    contextWindow: 8192,
    inputCostPer1kTokens: 0.03,
    outputCostPer1kTokens: 0.06,
  },
  {
    id: 'gemini-pro',
    label: 'Gemini Pro',
    provider: 'google',
    version: 'pro',
    description: 'Google\\'s versatile multimodal model for a wide range of tasks.',
    contextWindow: 32768,
    inputCostPer1kTokens: 0.00025,
    outputCostPer1kTokens: 0.0005,
  },
  {
    id: 'gemini-ultra',
    label: 'Gemini Ultra',
    provider: 'google',
    version: 'ultra',
    description: 'Google\\'s most capable model, designed for highly complex tasks.',
    contextWindow: 32768,
    inputCostPer1kTokens: 0.001,
    outputCostPer1kTokens: 0.002,
  },
  {
    id: 'claude-3-opus',
    label: 'Claude 3 Opus',
    provider: 'anthropic',
    version: '3-opus',
    description: 'Most intelligent model from Anthropic, excelling at complex reasoning and creativity.',
    contextWindow: 200000,
    inputCostPer1kTokens: 0.015,
    outputCostPer1kTokens: 0.075,
  },
  {
    id: 'claude-3-sonnet',
    label: 'Claude 3 Sonnet',
    provider: 'anthropic',
    version: '3-sonnet',
    description: 'Balanced model from Anthropic offering strong performance at a lower cost.',
    contextWindow: 200000,
    inputCostPer1kTokens: 0.003,
    outputCostPer1kTokens: 0.015,
  },
  {
    id: 'claude-3-haiku',
    label: 'Claude 3 Haiku',
    provider: 'anthropic',
    version: '3-haiku',
    description: 'Fastest and most compact model from Anthropic, ideal for quick responses.',
    contextWindow: 200000,
    inputCostPer1kTokens: 0.00025,
    outputCostPer1kTokens: 0.00125,
  },
];